### ISSUE TITLE
pull answer data from rsvp endpoint

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/meetupgoers#3]
## Problem

When people rsvp for events they complete answers to questions, and we are not capturing this.

## Solution

* Capture RSVP data from meetup api, https://www.meetup.com/meetup_api/docs/:urlname/events/:event_id/rsvps/#list.

### Requirement 
* do this for each event id we have
*  capture answers
    * meetup api give us a list, let's store each answer separately
* also capture the flowing info for each answer
  * question
  * question id
  * member id
  * group id

### Gotcha
* answers and questions may not always exist

can't happen in parallel with #5 , one will block the other

**Comment by gtungatkar** [comment]
Working on this, should be ready by tomorrow.

**Comment by gtungatkar** [comment]
@zassmin I am unable to get the answers in the rsvp response using the api key from heroku. I have been working with dummy data based on documentation. What am I missing?

**Comment by zassmin** [comment]
@gtungatkar not all events have rsvp info. I'll find you some that do!

**Comment by zassmin** [comment]
@gtungatkar 

This event has questions/answers, of course some people may be fill out answers, so some might be blank, but otherwise, it's a good example:
```
https://api.meetup.com/Women-Who-Code-SF/events/113887102/rsvps?fields=answers&key=somekey
```

It looks like you can find out which rsvps to pull if the event has questions. It goes without saying, make sure you are passing the answer field. 

Finding you some other ones now.

**Comment by zassmin** [comment]
To get same rsvp data a little more quickly I ran: 

```
https://api.meetup.com/Women-Who-Code-SF/events?fields=survey_questions&key=somekey
```

grabbed those event ids that had `survey_questions` key/value and ran a few requests, I emailed you the event ids I pulled with questions.
